authTime: 45 # время на авторизацию в секундах
bossBar: true # включен или выключен боссбар, с отображением времени
httpPort: 7000 # порт api

uuidGenerateKey: "super_secret_key" # ключ для генерации uuid